name: Run tests and deploy

on: push

jobs:
  ruun-tests:
    name: Publish package to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    # TODO dependencies cache
    - name: Install package and dependencies
      run: |
        python -m pip install pytest
        python -m pip install .
    - name: Run pytest
      run: python -m pytest -s tests
